name: The Gamby Files
favicon: null
layout_spectrum: 0.48869781172834337
typography_spectrum: 0.26329499762505293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.26046021073125303
  lightness: 0.026882113190367818
  saturation: 0.5508797285147011
  rhythmicContrast: 0.24402166972868145
purpose: []
